PXD-1430 Feat/simple metadata
uc-cdis/pidgin pull request #15
Opened 2018-08-06 20:05 UTC by paulineribeyre

If a file doesn't have core_metadata_collections, only retrieve the other metadata instead of returning an error. This is so that the landing page will not be broken if called on a file without core metadata

2018-08-06 20:44 UTC, rudyardrichter requested changes
I have a few small python/organizational things to suggest—otherwise, looks good :)

2018-08-06 20:44 UTC, rudyardrichter commented on pidgin/app.py
> +    citation_fields = ['creator', 'updated_datetime', 'title', 'publisher', 'object_id']
just for convention I would move this up to a global constant in this module, or have a `pidgin/constants.py` with this `CITATION_FIELDS` (and caps either way)

2018-08-06 20:44 UTC, rudyardrichter commented on pidgin/app.py
> +                if v:
can add this to the previous line:
```python
if k == 'core_metadata_collections' and v:
```

2018-08-06 20:44 UTC, rudyardrichter commented on pidgin/app.py
> +                    for _k, _v in v[0].items():
It looks like this loop could be replaced with `flat_d.update(v[0])`

2018-08-06 20:44 UTC, rudyardrichter commented on pidgin/app.py
> +        simple_query_txt = '''{{ {} (object_id: "{}") {{
This also seems like maybe a good candidate for a global constant (the `type`, `file_name`, etc. fields), which could be added to the query with
```python
' '.join(SIMPLE_QUERY_FIELDS)
```
(for example)

2018-08-06 20:44 UTC, rudyardrichter commented on pidgin/app.py
> +        simple_query_txt = '''{{ {} (object_id: "{}") {{
Better yet, a function to issue the "standard" simple query would be a great way to go.

2018-08-06 22:04 UTC, paulineribeyre commented on pidgin/app.py
> +                if v:
this doesn't work because if `not v`, the `else` block should not be executed

2018-08-07 15:55 UTC, rudyardrichter commented on pidgin/app.py
> +        response = send_query(simple_query_txt)
for both this one and the one above it now it can just go
```python
response = send_query(build_query(object_id, file_type, ...))
```

2018-08-07 15:55 UTC, rudyardrichter commented on pidgin/app.py
> +def build_query(object_id, file_type, get_core_metadata):
Would it make any sense to give `get_core_metadata` a default value? It seems like defaulting to False would be reasonable, what do you think?

2018-08-07 16:58 UTC, rudyardrichter approved these changes

2018-08-07 17:09 UTC, merged